University/Models/Course.cs
using System.ComponentModel.DataAnnotations;

namespace University.Models
{
    public class Course
    {
        [Required]
        public int CourseID { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        public int Credits { get; set; }
        public int Semester { get; set; }

        [StringLength(100)]
        public string? Programme { get; set; }

        [Display(Name = "Education Level")]
        [StringLength(25)]
        public string? EducationLevel { get; set; }

        public int? FirstTeacherID { get; set; }
        //[ForeignKey("FirstTeacherID")]
        [Display(Name = "First Teacher")]
        public Teacher? FirstTeacher { get; set; }
 
        public int? SecondTeacherID { get; set; }
        //[ForeignKey("SecondTeacherID")]
        [Display(Name = "Second Teacher")]
        public Teacher? SecondTeacher { get; set; }

        public ICollection<Enrollment>? Enrollments { get; set; }

    }
}

University/Models/Teacher.cs
using System.ComponentModel.DataAnnotations;

namespace University.Models
{
    public class Teacher
    {
        [Required]
        public int TeacherID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [StringLength(50)]
        public string? Degree { get; set; }

        [Display(Name = "Academic Rank")]
        [StringLength(25)]
        public string? AcademicRank { get; set; }

        [Display(Name = "Office Number")]
        [StringLength(10)]
        public string? OfficeNumber { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hire Date")]
        public DateTime? HireDate { get; set; }

        public string? ProfilePicture { get; set; }

        public string? userId { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get { return FirstName + " " + LastName; }
        }

        public ICollection<Course>? Course1 { get; set; }
        public ICollection<Course>? Course2 { get; set; }
    }
}

University/Controllers/TeachersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using University.Data;
using University.Models;
using University.ViewModels;

namespace University.Controllers
{
    public class TeachersController : Controller
    {
        private readonly UniversityContext _context;

        public TeachersController(UniversityContext context)
        {
            _context = context;
        }

        // GET: Teachers
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string searchIme, string searchPrezime, string searchDegree, string searchRank)
        {
            IQueryable<Teacher> teachers = _context.Teachers.AsQueryable();
            IQueryable<string> query = _context.Teachers.OrderBy(m => m.Degree).Select(m => m.Degree).Distinct();
            IQueryable<string> query1 = _context.Teachers.OrderBy(m => m.AcademicRank).Select(m => m.AcademicRank).Distinct();

            if (!string.IsNullOrEmpty(searchDegree))
            {
                teachers = teachers.Where(s => s.Degree.ToLower() == searchDegree.ToLower());
            }
            if (!string.IsNullOrEmpty(searchRank))
            {
                teachers = teachers.Where(s => s.AcademicRank.ToLower() == searchRank.ToLower());
            }
            if (!string.IsNullOrEmpty(searchIme))
            {
                teachers = teachers.Where(s => s.FirstName.ToLower().Contains(searchIme.ToLower()));
            }
            if (!string.IsNullOrEmpty(searchPrezime))
            {
                teachers = teachers.Where(s => s.LastName.ToLower().Contains(searchPrezime.ToLower()));
            }

            var VM1 = new FilterTeachers_VM
            {
                DegreeList = new SelectList(query.AsEnumerable()),
                RankList = new SelectList(query1.AsEnumerable()),
                Teachers = teachers.AsEnumerable()
            };


            return View(VM1);
        }

        [Authorize(Roles = "Admin,Teacher")]
        public IActionResult Courses(int? id)
        {
            IEnumerable<Course> courses = (IEnumerable<Course>)_context.Courses
                .Where(m => m.FirstTeacherID == id || m.SecondTeacherID == id);

            ViewData["Teacher"] = _context.Teachers.Where(s => s.TeacherID == id).Select(s => s.FullName).FirstOrDefault();

            return View(courses);
        }

        // GET: Teachers/Details/5
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Details(int? id, string? userID)
        {
            if (userID != null)
            {
                var tc = await _context.Teachers.FirstOrDefaultAsync(x => x.userId == userID);
                id = tc.TeacherID;
            }
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.TeacherID == id);
            if (teacher == null)
            {
                return NotFound();
            }

            Edit_TeacherPicture viewmodel = new Edit_TeacherPicture
            {
                Teacher = teacher,
                Desc = teacher.ProfilePicture
            };

            return View(viewmodel);
        }

        // GET: Teachers/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeacherID,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate,ProfilePicture,userId")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeacherID,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate,ProfilePicture,userId")] Teacher teacher)
        {
            if (id != teacher.TeacherID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.TeacherID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.TeacherID == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teachers.FindAsync(id);
            _context.Teachers.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teachers.Any(e => e.TeacherID == id);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditPicture(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = _context.Teachers.Where(x => x.TeacherID == id).First();
            if (teacher == null)
            {
                return NotFound();
            }

            Edit_TeacherPicture viewmodel = new Edit_TeacherPicture
            {
                Teacher = teacher,
                Desc = teacher.ProfilePicture   
            };

            return View(viewmodel);
        }

        // POST: Teachers/EditPicture/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPicture(long id, Edit_TeacherPicture viewmodel)
        {
            if (id != viewmodel.Teacher.TeacherID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (viewmodel.ProfileImage != null)
                    {
                        string uniqueFileName = UploadedFile(viewmodel);
                        viewmodel.Teacher.ProfilePicture = uniqueFileName;
                    }
                    else
                    {
                        viewmodel.Teacher.ProfilePicture = viewmodel.Desc;
                    }

                    _context.Update(viewmodel.Teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(viewmodel.Teacher.TeacherID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = viewmodel.Teacher.TeacherID });
            }
            return View(viewmodel);
        }
        private string UploadedFile(Edit_TeacherPicture viewmodel)
        {
            string uniqueFileName = null;

            if (viewmodel.ProfileImage != null)
            {
                //string uploadPath = Server.MapPath("~/images");
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(viewmodel.ProfileImage.FileName);

University/Views/Teachers/Courses.cshtml
@model IEnumerable<University.Models.Course>

@{
    ViewData["Title"] = "Courses";
}

<h3 style="color:darkblue"> Teacher: @ViewData["Teacher"]</h3>
<hr/>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationLevel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Programme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationLevel)
            </td>
            <td>
                <a asp-controller="Courses" asp-action="StudentsPoCourse" asp-route-id="@item.CourseID">Students</a> |
                <a asp-controller="Courses" asp-action="Edit" asp-route-id="@item.CourseID">Edit</a> |
                <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.CourseID">Details</a> |
                <a asp-controller="Courses" asp-action="Delete" asp-route-id="@item.CourseID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Index" style="font-weight:bolder">Back to List</a>
</div>

University/Views/Teachers/Create.cshtml
@model University.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<h3 style="color:darkblue">Add Teacher</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

University/Views/Teachers/Delete.cshtml
@model University.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h3 style="color:darkblue">Delete Teacher</h3>
<hr/>

<h4>Are you sure you want to delete this?</h4>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TeacherID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

University/Views/Teachers/Details.cshtml
@model University.ViewModels.Edit_TeacherPicture

@{
    ViewData["Title"] = "Details";
}

<h3 style="color:darkblue">Details for Teacher</h3>
<hr/>

<div>
    <h4>Teacher</h4>
    <hr />
     <span style="float:right">
    <dl class="row">
        <dd class = "col-sm-10">
            <img src="~/images/@Model.Teacher.ProfilePicture" height="220" width="150" style="margin-right:1cm;" asp-append-version="true" />
        </dd>
     </dl> 
     </span>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.HireDate)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="EditPicture" asp-route-id="@Model?.Teacher.TeacherID">Edit picture</a> 
        <span>|</span>
        <a asp-action="Edit" asp-route-id="@Model?.Teacher.TeacherID">Edit</a> <span>|</span>
        <a asp-action="Index">Back to List</a>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("Teacher"))
    {
        <a asp-controller="Home" asp-action="Index">Back</a>
    }
</div>

University/Views/Teachers/Edit.cshtml
@model University.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}

<h3 style="color:darkblue">Edit Teacher</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TeacherID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
             <div class="form-group" style="display:none">
                <label asp-for="ProfilePicture" class="control-label"></label>
                <input asp-for="ProfilePicture" class="form-control" readonly="@(true)">
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

University/Views/Teachers/EditPicture.cshtml
@model University.ViewModels.Edit_TeacherPicture

@{
    ViewData["Title"] = "EditPicture";
}


<h3 style="color:darkblue">Edit Teacher's Picture</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPicture" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Teacher.TeacherID" />
            <div class="form-group" >
                <label asp-for="Teacher.FirstName" class="control-label"></label>
                <input asp-for="Teacher.FirstName" class="form-control" readonly="@(true)"/>
                <span asp-validation-for="Teacher.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group" >
                <label asp-for="Teacher.LastName" class="control-label"></label>
                <input asp-for="Teacher.LastName" class="form-control" readonly="@(true)"/>
                <span asp-validation-for="Teacher.LastName" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Teacher.Degree" class="control-label"></label>
                <input asp-for="Teacher.Degree" class="form-control" />
                <span asp-validation-for="Teacher.Degree" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Teacher.AcademicRank" class="control-label"></label>
                <input asp-for="Teacher.AcademicRank" class="form-control" />
                <span asp-validation-for="Teacher.AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Teacher.OfficeNumber" class="control-label"></label>
                <input asp-for="Teacher.OfficeNumber" class="form-control" />
                <span asp-validation-for="Teacher.OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Teacher.HireDate" class="control-label"></label>
                <input asp-for="Teacher.HireDate" class="form-control" />
                <span asp-validation-for="Teacher.HireDate" class="text-danger"></span>
            </div>
             <div class="form-group" style="display:none">
                <label asp-for="Teacher.ProfilePicture" class="control-label"></label>
                <input asp-for="Desc" class="form-control" readonly="@(true)">
                <span asp-validation-for="Teacher.ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileImage" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="ProfileImage" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
     <a asp-action="Details" asp-route-id="@Model?.Teacher.TeacherID">Back to Details</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

University/Views/Teachers/Index.cshtml
@model University.ViewModels.FilterTeachers_VM

@{
    ViewData["Title"] = "Index";
}

<h1>Teachers</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Teachers" asp-action="Index" method="get">
    <span style="color:dodgerblue">First Name: </span><input type="text" asp-for="searchIme" />
    <span style="color:dodgerblue">Last Name: </span><input type="text" asp-for="searchPrezime" />
    <span style="color:dodgerblue">Degree : </span><select asp-for="searchDegree" asp-items="Model.DegreeList">
        <option value="">All</option>
    </select>
    Rank : <select asp-for="searchRank" asp-items="Model.RankList">
        <option value="">All</option>
    </select>
    <input type="submit" value="Filter" />
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Teachers.FirstOrDefault().FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers.FirstOrDefault().LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers.FirstOrDefault().Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers.FirstOrDefault().AcademicRank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers.FirstOrDefault().OfficeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers.FirstOrDefault().HireDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Teachers) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Degree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademicRank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            <td>
                <a asp-controller="Courses" asp-action="CoursesTeaching"  asp-route-id="@item.TeacherID">Courses</a> |  
                <a asp-action="Edit" asp-route-id="@item.TeacherID">Edit</a> | 
                <a asp-action="Details" asp-route-id="@item.TeacherID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TeacherID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>