University/Models/Enrollment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace University.Models
{
    public class Enrollment
    {
        public long EnrollmentID { get; set; }

        [Required]
        public int CourseID { get; set; }
        public Course? Course { get; set; }

        [Required]
        public long StudentID { get; set; }
        public Student? Student { get; set; }

        [StringLength(10)]
        public string? Semester { get; set; }

        public int? Year { get; set; }
        public int? Grade { get; set; }

        [StringLength(255)]
        [Display(Name = "Seminal Url")]
        public string? SeminalUrl { get; set; }

        [Display(Name = "Project Url")]
        [StringLength(255)]
        public string? ProjectUrl { get; set; }

        [Display(Name = "Exam Points")]
        public int? ExamPoints { get; set; }

        [Display(Name = "Seminal Points")]
        public int? SeminalPoints { get; set; }

        [Display(Name = "Project Points")]
        public int? ProjectPoints { get; set; }

        [Display(Name = "Additional Points")]
        public int? AdditionalPoints { get; set; }

        [Display(Name = "Finish Date")]
        public Nullable<DateTime> FinishDate { get; set; }


        [Display(Name = "Total Points")]
        public int TotalPoints
        {
            get
            {
                if (ExamPoints == null)
                    ExamPoints = 0;
                if (SeminalPoints == null)
                    SeminalPoints = 0;
                if (ProjectPoints == null)
                    ProjectPoints = 0;
                if (AdditionalPoints == null)
                    AdditionalPoints = 0;
                int points = (int)(ExamPoints + SeminalPoints + ProjectPoints + AdditionalPoints);
                return (int)points;
            }
        }
    }
}

University/Controllers/EnrollmentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using University.Data;
using University.Models;
using University.ViewModels;

namespace University.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly UniversityContext _context;
        public EnrollmentsController(UniversityContext context)
        {
            _context = context;
        }

        // GET: Enrollments
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Index()
        {
            var universityContext = _context.Enrollments.Include(e => e.Student).Include(e => e.Course).ThenInclude(e=>e.FirstTeacher);
            universityContext = universityContext.Include(e => e.Course).ThenInclude(e => e.SecondTeacher);
           
            return View(await universityContext.ToListAsync());
        }

        //Create
        [Authorize(Roles="Admin")]
        public IActionResult Index1()
        {
            ViewData["CourseID"] = new SelectList(_context.Courses, "CourseID", "CourseID");
            ViewData["StudentID"] = new SelectList(_context.Students, "ID", "ID");

            return View();
        }

        [Authorize(Roles="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index1([Bind("EnrollmentID,CourseID,StudentID,Semester,Year")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CourseID"] = new SelectList(_context.Courses, "CourseID", "CourseID", enrollment.CourseID);
            ViewData["StudentID"] = new SelectList(_context.Students, "ID", "ID", enrollment.StudentID);
            return View(enrollment);
        }

        // GET: Enrollments/Details/5
        [Authorize(Roles="Admin,Student,Teacher")]
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        //[Authorize(Roles="Admin")] ??nz dali mi treba ovaa akcija
        public IActionResult Create()
        {
            ViewData["CourseID"] = new SelectList(_context.Courses, "CourseID", "Title");
            ViewData["StudentID"] = new SelectList(_context.Students, "ID", "FirstName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles="Admin")] ??
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnrollmentID,CourseID,StudentID,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseID"] = new SelectList(_context.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewData["StudentID"] = new SelectList(_context.Students, "ID", "FirstName", enrollment.StudentID);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["CourseID"] = new SelectList(_context.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewData["StudentID"] = new SelectList(_context.Students, "ID", "FirstName", enrollment.StudentID);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("EnrollmentID,CourseID,StudentID,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (id != enrollment.EnrollmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.EnrollmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseID"] = new SelectList(_context.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewData["StudentID"] = new SelectList(_context.Students, "ID", "FirstName", enrollment.StudentID);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [Authorize(Roles="Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var enrollment = await _context.Enrollments.FindAsync(id);
            _context.Enrollments.Remove(enrollment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(long id)
        {
            return _context.Enrollments.Any(e => e.EnrollmentID == id);
        }

        [Authorize(Roles="Admin,Teacher")]
        public async Task<IActionResult> ListEnrolledStudents(int? id, string teacher, int year)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.CourseID== id);

            string[] names = teacher.Split(" ");
            var teacherModel = await _context.Teachers.FirstOrDefaultAsync(m => m.FirstName == names[0] && m.LastName == names[1]);
            ViewBag.teacher = teacher;
            ViewBag.course = course.Title;
            var enrollment = _context.Enrollments.Where(x => x.CourseID == id && (x.Course.FirstTeacherID == teacherModel.TeacherID || x.Course.SecondTeacherID == teacherModel.TeacherID))
            .Include(e => e.Course)
            .Include(e => e.Student);
            await _context.SaveChangesAsync();
            IQueryable<int?> yearsQuery = _context.Enrollments.OrderBy(m => m.Year).Select(m => m.Year).Distinct();
            IQueryable<Enrollment> enrollmentQuery = enrollment.AsQueryable();
            if (year != null && year != 0)
            {
                enrollmentQuery = enrollmentQuery.Where(x => x.Year == year);
            }
            else
            {
                enrollmentQuery = enrollmentQuery.Where(x => x.Year == yearsQuery.Max());
            }

            if (enrollment == null)
            {
                return NotFound();
            }

            FilterEnrollment viewmodel = new FilterEnrollment
            {
                Enrollments = await enrollmentQuery.ToListAsync(),
                listYears = new SelectList(await yearsQuery.ToListAsync())
            };

            return View(viewmodel);
        }

        // GET: Enrollments/EditAsTeacher/5
       [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> EditAsTeacher(long? id, string teacher)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewBag.teacher = teacher;
            ViewData["CourseID"] = new SelectList(_context.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewData["StudentID"] = new SelectList(_context.Students, "ID", "FirstName", enrollment.StudentID);
            return View(enrollment);

University/Views/Enrollments/Create.cshtml
@model University.Models.Enrollment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseID" class="control-label"></label>
                <select asp-for="CourseID" class ="form-control" asp-items="ViewBag.CourseID"></select>
            </div>
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <select asp-for="StudentID" class ="form-control" asp-items="ViewBag.StudentID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalUrl" class="control-label"></label>
                <input asp-for="SeminalUrl" class="form-control" />
                <span asp-validation-for="SeminalUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectUrl" class="control-label"></label>
                <input asp-for="ProjectUrl" class="form-control" />
                <span asp-validation-for="ProjectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamPoints" class="control-label"></label>
                <input asp-for="ExamPoints" class="form-control" />
                <span asp-validation-for="ExamPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalPoints" class="control-label"></label>
                <input asp-for="SeminalPoints" class="form-control" />
                <span asp-validation-for="SeminalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPoints" class="control-label"></label>
                <input asp-for="ProjectPoints" class="form-control" />
                <span asp-validation-for="ProjectPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalPoints" class="control-label"></label>
                <input asp-for="AdditionalPoints" class="form-control" />
                <span asp-validation-for="AdditionalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

University/Views/Enrollments/Delete.cshtml
@model University.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
}

<h3 style="color:darkred"> Delete Enrollment</h3>
<hr/>
<h4>Are you sure you want to delete this?</h4>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EnrollmentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

University/Views/Enrollments/Details.cshtml
@model University.Models.Enrollment

@{
    ViewData["Title"] = "Details";
}

<h3 style="color:darkblue">Details for Enrollment</h3>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>
    </dl>
</div>
<div>
     @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")){
    <a asp-action="Edit" asp-route-id="@Model?.EnrollmentID">Edit</a>
    <span>|</span>
    <a asp-action="Index">Back to List</a>
     }
      @if (User.Identity.IsAuthenticated && User.IsInRole("Student"))
    {
        <a asp-action="EditAsStudent" asp-route-id="@Model?.StudentID">Edit</a>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("Teacher")){
                    
    <a asp-controller="Courses" asp-action="CoursesTeaching" asp-route-id="@Model?.CourseID">Back to Courses</a>
    }
</div>

University/Views/Enrollments/Edit.cshtml
@model University.Models.Enrollment

@{
    ViewData["Title"] = "Edit";
}

<h3 style="color:darkblue">Edit Enrollment</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EnrollmentID" />
            <div class="form-group">
                <label asp-for="CourseID" class="control-label"></label>
                <select asp-for="CourseID" class="form-control" asp-items="ViewBag.CourseID"></select>
                <span asp-validation-for="CourseID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <select asp-for="StudentID" class="form-control" asp-items="ViewBag.StudentID"></select>
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalUrl" class="control-label"></label>
                <input asp-for="SeminalUrl" class="form-control" />
                <span asp-validation-for="SeminalUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectUrl" class="control-label"></label>
                <input asp-for="ProjectUrl" class="form-control" />
                <span asp-validation-for="ProjectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamPoints" class="control-label"></label>
                <input asp-for="ExamPoints" class="form-control" />
                <span asp-validation-for="ExamPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalPoints" class="control-label"></label>
                <input asp-for="SeminalPoints" class="form-control" />
                <span asp-validation-for="SeminalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPoints" class="control-label"></label>
                <input asp-for="ProjectPoints" class="form-control" />
                <span asp-validation-for="ProjectPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalPoints" class="control-label"></label>
                <input asp-for="AdditionalPoints" class="form-control" />
                <span asp-validation-for="AdditionalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

University/Views/Enrollments/ListEnrolledStudents.cshtml
@model University.ViewModels.FilterEnrollment
@{
    ViewData["Title"] = "Index";
}

<h3 style="color:darkblue">Enrolled students at "@ViewBag.course" from teacher "@ViewBag.teacher"</h3>
<hr/>

<form asp-controller="Enrollments" asp-action="ListEnrolledStudents" asp-route-teacher="@ViewBag.teacher">
    <p>
        Year: <select asp-for="Year" asp-items="Model.listYears">
            <option>Select year</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].SeminalUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ProjectUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ExamPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].SeminalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ProjectPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].AdditionalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].TotalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].FinishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Enrollments) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @if(@item.SeminalUrl != null)
                {    
                        <a href="\seminals\@item.SeminalUrl">Open seminal file</a>
                    }
                    else
                    {
                        <span>No file uploaded</span>
                    }
            </td>
            <td>
                 @if(@item.ProjectUrl != null)
                {    
                        <a href="@item.ProjectUrl">Open project link</a>
                    }
                    else
                    {
                        <span>No link uploaded</span>
                    }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExamPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeminalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdditionalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td>
                @if (item.FinishDate == null)
                {
                    <a asp-action="EditAsTeacher" asp-route-id="@item.EnrollmentID" asp-route-teacher="@ViewBag.teacher">Edit</a>
                    <span> |</span>
                }
                <a asp-action="Details" asp-route-id="@item.EnrollmentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.EnrollmentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>